services:
  - docker

before_install:
  - docker build -t malacko/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true malacko/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react-frontend"
  env: "Docker-react-frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-725651562557"
  bucket_path: "docker-react-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  
